로그인, 회원가입 , 홈 페이지
KimKiHyun0206/SELab-ToyProject-2024 pull request #12
Opened 2024-07-08 19:23 UTC by kyungmin0228

메인 , 로그인 , 회원가입 html 만들었습니다

2024-07-08 23:20 UTC, KimKiHyun0206 commented
실행 화면 스크린샷 찍어서 올리세요

2024-07-09 04:16 UTC, kyungmin0228 commented
![로그인 페이지](https://github.com/kangsangmoon/SELab-ToyProject-2024/assets/169899220/c435398d-a995-494b-98b6-fcefa92c2745)
![메인페이지](https://github.com/kangsangmoon/SELab-ToyProject-2024/assets/169899220/093d3a0a-b70e-4694-b917-4131975640a9)
![회원가입페이지](https://github.com/kangsangmoon/SELab-ToyProject-2024/assets/169899220/47bc224d-6170-4369-8ce2-25523939867c)

2024-07-09 04:21 UTC, KimKiHyun0206 commented
문자들 위아래 간격이 여유가 없습니다.
그리고 회원가입 절차가 너무 간단합니다. 이메일 인증도 할 수 있도록 만들어주세요.
그리고 언어는 하나로 통일해주세요 Login 처럼 영어로 할지 회원가입처럼 한국어로 할지

2024-07-09 04:21 UTC, KimKiHyun0206 commented
그리고 회원가입과 로그인 페이지 모두에 네지게이션 바가 필요할까요

2024-07-20 14:54 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
Restful 한 URL이 아닙니다. URL에 대한 규칙을 공부하고 적용해보세요

2024-07-20 14:56 UTC, KimKiHyun0206 requested changes
실행된 HTML 페이지를 스크린샷 찍어서 올려주세요

2024-07-20 14:56 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +}
Restful 한 URL이 아닙니다. URL에 대한 규칙을 공부하고 적용해보세요

2024-07-20 14:56 UTC, KimKiHyun0206 commented on build.gradle
나중에 merge할 때 주석처리한 부분은 모두 돌려놓고 merge활 수 있도록 해주세요

2024-07-20 15:20 UTC, KimKiHyun0206 commented
template 폴더에 들어있는 html들 이름을 남들도 알 수 있게 규칙을 정해서 다시 명명해주세요.
그리고 폴더 안에 또다른 폴더를 만들어서 가독성을 좋게 해주세요.

2024-07-21 17:46 UTC, kyungmin0228 commented
로그인 화면과 회원가입 화면으로 넘어가려 하면 화이트라벨이 뜹니다

2024-07-22 08:55 UTC, KimKiHyun0206 requested changes
실행 가능한 코드를 올려주세요. 그리고 HTML은 필수적으로 실행 화면 스크린 샷을 찍어서 올려야합니다.

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +
올바르지 않은 패키지명입니다. 저번에 카톡방에 공유한 이름짓기 법을 다시 공부하세요

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +
마찬가지입니다 올바르지 않은 패키지명입니다. 저번에 카톡방에 공유한 이름짓기 방법을 다시 공부하세요

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
모든 메소드의 마지막에 Page가 붙는데 필요할까요? 메소드명을 간소화하여 지읍시다.

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
login.do 는 어떤 처리 방식인가요?

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
loginForm은 어떤 객체인가요. 이 브랜치에는 LoginForm이라는 클래스는 존재하지 않습니다.

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/signup_page.html
> +            <form th:action="@{/signup.do}" th:object="${signupForm}" method="post">
signupForm은 어떤 객체인가요. 이 브랜치에 SignupForm이라는 클래스는 존재하지 않습니다

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/signup_page.html
> +            <form th:action="@{/signup.do}" th:object="${signupForm}" method="post">
그리고 signup.do도 어떤 메소드인지 알 수 없습니다

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/problems_list.html
> +            <td th:text="${problmes.ratio}">ratio</td>
problemList는 어떤 객체인가요. 이 브랜치에 ProblemList라는 클래스는 존재하지 않습니다. 그리고 각 변수가 의미하는 것은 뭔가요. 어떤 의미를 가지고 변수명을 지은 건지 알 수 없습니다

2024-07-22 08:55 UTC, KimKiHyun0206 commented on src/main/resources/templates/signin_main_page.html
> +            <a th:href="@{/main}">로그아웃</a>
my_page라는 html은 존재하지 않습니다.

2024-07-23 01:17 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
확인했습니다

2024-07-23 04:10 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +
수정했습니다

2024-07-23 04:10 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +
수정했습니다

2024-07-23 04:11 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
package com.example.project;


import lombok.Data;

@Data
public class loginForm {
    public static void main(String[] args) {
        loginForm loginForm = new loginForm();
    }

    private String userId;
    private String password;

}

2024-07-23 04:11 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
이런식으로 작성했습니다

2024-07-23 04:12 UTC, kyungmin0228 commented on src/main/resources/templates/signin_main_page.html
> +            <a th:href="@{/main}">로그아웃</a>
수정했습니다

2024-07-23 04:12 UTC, kyungmin0228 commented on src/main/resources/templates/problems_list.html
> +            <td th:text="${problmes.ratio}">ratio</td>
problemList html 삭제 했습니다

2024-07-23 04:13 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
@PostMapping("/login.do")
    public String login(@Validated loginForm loginForm, Model model, HttpServletRequest request, BindingResult result,
                        RedirectAttributes redirect, HttpServletResponse response)throws Exception  {
        return "login/before/signin_main";
    }

2024-07-23 04:13 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
위 코드로 작성했습니다

2024-07-23 04:18 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
왜 main 함수가 들어가나요

2024-07-23 04:18 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
그리고 markdown 에 대해서 공부하고 pr에 리플을 달아주세요

2024-07-23 04:38 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
확인 했습니다

2024-07-23 09:39 UTC, kyungmin0228 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
마크다운 공부 했습니다

2024-07-23 11:20 UTC, KimKiHyun0206 commented
수정한 Commit이 없는데요

2024-07-23 14:12 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
url 규칙에 맞지 않습니다. 제대로 공부한 후에 작성해주세요

2024-07-23 14:13 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
loginForm 클래스는 클래스 이름 짓는 방법이 잘못되었습니다. 클래스 이름은 대문자로 시작하는 카멜케이스입니다.

2024-07-23 14:13 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
Controller 부분에서 예외를 throw하면 throw한 예외는 어디서 처리해주나요

2024-07-23 14:14 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
> 마크다운 공부 했습니다

공부를 했다면 위에 작성한 코드가 저런식으로 나오지 않겠죠

2024-07-23 14:15 UTC, KimKiHyun0206 commented on src/main/resources/templates/problems_list.html
> +            <td th:text="${problmes.ratio}">ratio</td>
삭제하지 않았는데요

2024-07-23 14:18 UTC, KimKiHyun0206 commented on src/main/resources/templates/beforelogin/login_page.html
> +                <input type="text" th:field="*{userId}" placeholder="아이디" id="userId" required>
> @PostMapping("/login.do") public String login(@validated loginForm loginForm, Model model, HttpServletRequest request, BindingResult result, RedirectAttributes redirect, HttpServletResponse response)throws Exception { return "login/after/signin_main"; }

![image](https://github.com/user-attachments/assets/3e527449-2e26-4266-a44d-75c768b40d78)

분명히 전에 공부해보라고 했는데 왜 적용이 안됐을까요

2024-07-23 16:05 UTC, KimKiHyun0206 requested changes

2024-07-23 16:05 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginForm.java
> +
이건 무슨 코드죠 설명해주세요

2024-07-23 16:05 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
본 메소드에서 매개변수로 받는 인스턴스들을 사용되지 않습니다.
추가된 이유가 뭔가요.

2024-07-23 16:05 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +        return "login/aftre/signin_main";
전에도 말했지만 먼저 사용하지 않는 매개변수들입니다.
추가된 이유가 뭔가요.
그리고 이전 리뷰에서도 말했듯이 예외를 컨트롤러 단에서 밖으로 던지면 예외를 어디서 처리해주나요.

2024-07-23 16:05 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
>                  <label>아이디</label>
SignupForm이라는 객체가 존재하지 않습니다.
존재하지 않는 객체를 계속해서 사용하는 이유가 뭔가요.

2024-07-23 16:09 UTC, KimKiHyun0206 commented
실행 화면 보여주세요

2024-07-24 04:52 UTC, kyungmin0228 commented
![image](https://github.com/user-attachments/assets/1af8158c-c0ad-4408-8b26-bb5b7f601155)

2024-07-24 04:52 UTC, kyungmin0228 commented
![image](https://github.com/user-attachments/assets/bddcd71c-7532-4a54-874c-a473465ecf3b)

화면 올렸습니다

2024-07-24 04:53 UTC, kyungmin0228 commented on src/main/resources/templates/login/before/signup.html
>                  <label>아이디</label>
컨트롤러에서 빈 객체 만들도록 했습니다

2024-07-24 04:53 UTC, kyungmin0228 commented on src/main/java/com/example/project/LoginForm.java
> +
컨트롤러에서 객체를 만들도록 했습니다

2024-07-24 04:55 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
```@GetMapping("/login")
    public String loginPage(Model model) {
        model.addAttribute("LoginForm", new LoginForm());
        return "login/before/login";
    }```
    이렇게 수정했습니다

2024-07-24 04:56 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +        return "login/aftre/signin_main";
이부분은 삭제했습니다

2024-07-24 04:57 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
`@GetMapping("/login")
    public String loginPage(Model model) {
        model.addAttribute("LoginForm", new LoginForm());
        return "login/before/login";
    }`

2024-07-24 04:57 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
이런식으로 수정했습니다.

2024-07-24 05:13 UTC, kyungmin0228 commented on src/main/java/com/example/project/controller/HomeController.java
> +        return "login/aftre/signin_main";
이 부분이 필요한 부분인가요?

2024-07-24 11:37 UTC, KimKiHyun0206 requested changes
모두 오류 없이 실행되는지 실행 시켜보고 알려주세요

2024-07-24 11:37 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
확인했으면 해결을 하세요

2024-07-24 11:37 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
이메일 인증 버튼도 추가해주세요.

2024-07-24 11:40 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/controller/HomeController.java
> +    }
마크다운 공부를 다시 해보세요.
```java
@GetMapping("/login") 
public String loginPage(Model model) {
    model.addAttribute("LoginForm", new LoginForm()); 
    return "login/before/login"; 
}
```
이런식으로 쓸 수 있습니다

2024-07-24 11:41 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
>                  <label>아이디</label>
컨트롤러에서 빈 객체를 만든다는 게 무슨 말이죠?

2024-07-24 11:41 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
>                  <label>아이디</label>
코드에는 빈 객체를 만드는 내용이 없습니다.

2024-07-26 06:00 UTC, kyungmin0228 commented on src/main/resources/templates/login/before/signup.html
이메일 인증 버튼 추가 했습니다

2024-07-26 06:28 UTC, kyungmin0228 commented on src/main/resources/templates/login/before/signup.html
![image](https://github.com/user-attachments/assets/4ca2af32-84e2-4703-a125-36ab19fe7f25)

2024-07-26 06:30 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
> +                <input type="text" th:field="*{emailCheck}" placeholder="인증번호 입력">
버튼 누르면 아무것도 실행되는 게 없는 거 같은데 누르면 뭔가 실행되게 만들어주세요

2024-07-26 06:33 UTC, KimKiHyun0206 commented on src/main/resources/templates/login/before/signup.html
이메일 받기 버튼은 인증 번호 입력 칸 옆에 만들어주세요

2024-07-26 06:34 UTC, kyungmin0228 commented on src/main/resources/templates/login/before/signup.html
> +                <input type="text" th:field="*{emailCheck}" placeholder="인증번호 입력">
확인했습니다

2024-08-17 07:52 UTC, closed without merging