쿠키 생성, 조회, 삭제
KimKiHyun0206/SELab-ToyProject-2024 pull request #15
Opened 2024-07-16 09:06 UTC by JOOKITEZ

로그인 시 쿠키 생성, 조회
로그아웃 시 쿠키 삭제하는 코드를 작성했습니다.

2024-07-16 14:12 UTC, KimKiHyun0206 commented
쿠키 생성, 조회, 삭제는 커밋명으로 적절하지 않습니다. Wiki를 읽어보고 앞으로는 제대로 된 커밋명을 작성해주세요

2024-07-16 14:19 UTC, KimKiHyun0206 commented
왜 .java의 파일들이 main 아래에 위치해있나요. 실행은 해보셨나요?

2024-07-16 14:20 UTC, KimKiHyun0206 commented
Class의 이름은 맨 앞을 대문자로 시작하는 카멜케이스입니다

2024-07-16 15:20 UTC, KimKiHyun0206 requested changes

2024-07-16 15:20 UTC, Duskafka commented on src/main/loginCookie/createcookie.java
> +@PostMapping("login")
Restful 한 URL이 아닙니다. URL 규칙을 공부하고 다시 적용해주세요

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/createcookie.java
> +public String login(@Valid @ModelAttribute LoginForm form, BindingResult bindingResult, HttpServletResponse response) {
LoginFrom과 BindingResult는 어떤 객체인가요?

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/createcookie.java
> +    Member loginMember = loginService.login(form.getLoginId(), form.getPassword());
생성된 LoginService 객체는 어디에 있나요. 그리고 LoginService 클래스가 존재하지 않습니다.

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/createcookie.java
> +    Cookie idCookie = new Cookie("memberId", String.valueOf(loginMember.getId()));
Member의 데이터베이스 상 ID를 쿠키로 남기면 보안 상 큰 문제가 될 수 있습니다.

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/deletecookie.java
> +} //서버에서 쿠키 없애기(로그아웃 할 때)
1. 따로 메소드를 분리할 이유가 있을까요?
2. HttpServletResponse response 객체는 받아서 사용하지 않는데, 왜 매개변수로 받아온 건가요?

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/deletecookie.java
> +}
HttpServletRequest에서 쿠키를 받아오지 않았는데 어떤 쿠키를 지우는 건가요?
쿠키가 존재하는지 확인하는 로직을 먼저 작성해야 합니다.

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/searchcookie.java
> +    Member loginMember = memberRepository.findById(memberId);
1. Member는 어떤 클래스인가요
2. memberRepository는 는 어떤 객체이며 findById는 어떤 메소드인가요?

위 로직에 따르면 로그인 하는 방법은 패스워드가 필요 없고 아이디만 필요한데 이는 너무 안일한 로그인 방식 아닐까요?

2024-07-16 15:20 UTC, KimKiHyun0206 commented on src/main/loginCookie/searchcookie.java
> +    return "loginHome";
어떤 HTML로 객체를 넘겨주는 건가요?

2024-07-20 15:05 UTC, KimKiHyun0206 requested changes
앞으로는 실행 가능한 코드를 push해주세요

2024-07-20 15:05 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginController.java
> +        if (loginUser == null) {
무조건적으로 false문이 나오는 구문인데 구문에 의미가 있나요?

2024-07-20 15:05 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginController.java
> +            return "login_error_form";
위의 코드와 중복됩니다. 수정이 필요합니다

2024-07-21 10:17 UTC, JOOKITEZ commented on src/main/java/com/example/project/LoginController.java
> +        if (loginUser == null) {
코드에 에러가 하나 있어서 고치는 도중 구글링을 통해 id값이 null일 경우 오류가 발생할 수 있다고 해서 그렇게 고쳐봤었습니다. 원래 상태로 돌려놓겠습니다!

2024-07-21 10:27 UTC, JOOKITEZ commented on src/main/java/com/example/project/LoginController.java
> +            return "login_error_form";
수정했습니다!

2024-07-21 13:11 UTC, JOOKITEZ commented
코드가 실행이 안 되는 이유가 아직 데이터베이스와 연결이 되지 않아 안 되는 것 같습니다. 내일까지 데이터베이스 연결시켜서 실행되도록 하겠습니다.

2024-07-21 13:58 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginService.java
>                  return new User(
password 에서 encryptedPassword 으로 바꾸면 제대로 실행이 안될텐데 실행 해보셨나요?

2024-07-22 10:46 UTC, JOOKITEZ commented on src/main/java/com/example/project/LoginService.java
>                  return new User(
인텔리제이에서 Run을 해보았는데 데이터베이스가 아직 연결이 되지 않아 오류가 떴다는 것만 확인되어서 실행이 된다고 생각했습니다...!
![스크린샷 2024-07-22 194534](https://github.com/user-attachments/assets/3393e1bd-72ec-400c-97bc-f8488b669f78)

2024-07-22 12:09 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginService.java
>                  return new User(
데이터베이스 설치하세요

2024-07-22 13:25 UTC, Duskafka commented on src/main/java/com/example/project/LoginService.java
>              String encryptedPassword = encryptPassword(password);// 비밀번호 암호화해서 저장된 비밀번호와 비교
이 부분이 수정되었는데 왜 수정된건지 알려주세요

2024-07-22 13:31 UTC, JOOKITEZ commented on src/main/java/com/example/project/LoginService.java
>              String encryptedPassword = encryptPassword(password);// 비밀번호 암호화해서 저장된 비밀번호와 비교
get()일 때 경고문구가 떠서 없애는 방법을 찾던 도중 위와 같이 수정하면 경고문구를 없앨 수 있다고 해서 수정했습니다!

2024-07-22 13:35 UTC, Duskafka commented on src/main/java/com/example/project/LoginService.java
>              String encryptedPassword = encryptPassword(password);// 비밀번호 암호화해서 저장된 비밀번호와 비교
알겠습니다

2024-07-25 06:25 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/LoginController.java
>  }
로그아웃은 GetMapping이 아니라 PostMapping을 사용합니다

2024-07-25 10:55 UTC, JOOKITEZ commented on src/main/java/com/example/project/LoginController.java
>  }
수정했습니다!

2024-07-25 10:57 UTC, KimKiHyun0206 commented
여기서 공부했던 내용을 토대로 HTML 통합 이후에 로그인 로직과 함께 쿠키 로직을 작성해주세요

2024-07-25 11:15 UTC, JOOKITEZ commented
넵!

2024-07-25 14:04 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/CookieService.java
> +    }
Lombok 애노테이션을 사용해서 코드를 간소화합시다

2024-07-25 14:04 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/EncryptionService.java
> +        }
이러면 예외를 처리하는 게 아니라 예외를 밖으로 던지는 게 됩니다.

2024-07-27 10:48 UTC, JOOKITEZ commented on src/main/java/com/example/project/CookieService.java
> +    }
수정했습니다!

2024-07-27 10:49 UTC, JOOKITEZ commented on src/main/java/com/example/project/EncryptionService.java
> +        }
예외 처리할 수 있도록 수정했습니다!

2024-07-27 12:35 UTC, KimKiHyun0206 commented
잘했어요

2024-07-27 12:59 UTC, JOOKITEZ commented
감사합니다!!

2024-08-17 05:40 UTC, closed without merging