[ 김동건 ] 코드 리뷰 부탁드립니다
KimKiHyun0206/SELab-ToyProject-2024 pull request #20
Opened 2024-08-17 06:18 UTC by KimKiHyun0206

# 작업 내용
* User(사용자), Board(게시판), Comment(게시판 댓글), Solution(코딩 문제)
* 쿠키와 세션을 통한 로그인 확인

# 리뷰 부탁드리는 내용
* 추가로 적용하면 좋을 것 같은 기술
* 객체지향적 설계에 맞지 않는 설계가 있는지

위 두가지에 대해서 리뷰 부탁드리고 싶습니다.

2024-08-19 00:55 UTC, DongGeon0908 requested changes
1. restController, controller의 path를 특정 규칙을 지키며 사용하도록 수정
2. 이슈 기반으로 어떤 작업들을 진행할 것인지 목록화 필요.

2024-08-19 00:55 UTC, DongGeon0908 commented on src/main/java/com/example/project/board/controller/BoardApiController.java
> +@RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE, value = "/api/boards")
"/api/v1/boards"

2024-08-19 00:55 UTC, DongGeon0908 commented on src/main/java/com/example/project/board/repository/BoardRepository.java
@Transactional(readOnly = true)

2024-08-22 14:35 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/board/controller/BoardApiController.java
> +@RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE, value = "/api/boards")
확인했습니다

2024-08-22 14:35 UTC, KimKiHyun0206 commented on src/main/java/com/example/project/board/repository/BoardRepository.java
확인했습니다

2024-08-24 13:42 UTC, closed without merging